Global Refactoring

diff --git a/.github/workflows/license_update.yml b/.github/workflows/license_update.yml
--- a/.github/workflows/license_update.yml
+++ b/.github/workflows/license_update.yml
@@ -15,13 +15,17 @@ jobs:
         LICENSE_FILE: LICENSE.md
       run: |
         CURRENT_YEAR=$(date +%Y)
-        grep -P "$LICENSE_REGEX" -Rl . 
+        FILES=0
         while IFS= read -r FILE; do
-          echo "$FILE"
+          PATTERN=$(grep -Poh "$LICENSE_FILE" "$FILE")
+          sed -i "s/$PATTERN/2019-$CURRENT_YEAR/g" "$FILE"
+          grep -P "$LICENSE_FILE" "$FILE"
+          COUNTER=$((COUNTER+1))
         done < <(grep -P "$LICENSE_REGEX" -Rl .)
-        exit 1
-        sed -i "s/$LICENSE_REGEX/2019-$CURRENT_YEAR/g" "$LICENSE_FILE"
-        grep -P "$LICENSE_REGEX" "$LICENSE_FILE"
+        if [[ "$COUNTER -ne 5 ]]; then
+          echo "INVALID NUMBER OF FILES"
+          exit 1
+        fi
         git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
         git config --local user.name "${{ secrets.BOT_USERNAME }}"
         git config --local user.email "${{ secrets.BOT_EMAIL }}"
